[versions]
android-gradle-plugin = "9.3.1"
jgit = "7.7.1.202607240634-r"
json = "20260814"

[libraries]
# Build script
jgit = { group = "org.eclipse.jgit", name = "org.eclipse.jgit", version.ref = "jgit" }
jgit-archive = { group = "org.eclipse.jgit", name = "org.eclipse.jgit.archive", version.ref = "jgit" }
json = { group = "org.json", name = "json", version.ref = "json" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
