---
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Validate gradle wrapper checksum
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 20
          cache: gradle

      - name: Build and test
        run: ./gradlew --no-daemon build zipRelease
